spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
    url: jdbc:mysql://101.200.210.89:3306/vhr?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai

#  rabbitmq:
#    username: guest
#    password: guest
#    host: 127.0.0.1
#    publisher-confirms: true
#    publisher-returns: true
  redis:
    host: 47.105.158.78
    database: 0
    port: 6399
    password:
  cache:
    cache-names: menus_cache
server:
  port: 8069
  compression:
    enabled: true
fastdfs:
  nginx:
    host: http://192.168.91.128/