export CATALINA_OPTS="$CATALINA_OPTS -Xms$JVM_XMS"
export CATALINA_OPTS="$CATALINA_OPTS -Xmx$JVM_XMX"
export CATALINA_OPTS="$CATALINA_OPTS -Xmn$JVM_XMN"
export CATALINA_OPTS="$CATALINA_OPTS -XX:MetaspaceSize=128m"
export CATALINA_OPTS="$CATALINA_OPTS -XX:MaxMetaspaceSize=256m"
export CATALINA_OPTS="$CATALINA_OPTS -XX:MaxDirectMemorySize=1024m"
export CATALINA_OPTS="$CATALINA_OPTS -XX:+UnlockExperimentalVMOptions"
export CATALINA_OPTS="$CATALINA_OPTS -XX:+UseCGroupMemoryLimitForHeap"
#export CATALINA_OPTS="$CATALINA_OPTS -Dspring.profiles.active=$ACTIVE_PROFILE"
export CATALINA_OPTS="$CATALINA_OPTS -Duser.language=zh -Duser.country=CN -Duser.timezone=$TZ"
export CATALINA_OPTS="$CATALINA_OPTS -verbose:gc"
export CATALINA_OPTS="$CATALINA_OPTS -Xloggc:/root/logs/java/gc.log"
export CATALINA_OPTS="$CATALINA_OPTS -XX:+PrintGCDetails"
export CATALINA_OPTS="$CATALINA_OPTS -XX:+PrintGCDateStamps"